### ISSUE TITLE
Additional Icons for vscode-deephaven extension

### ISSUE THREAD

**Issue by bmingles** [deephaven/vscode-deephaven#13]
The vscode-deephaven extension could use a few additional icons

- Differentiate connected vs disconnected. Default product icons only include this one 
  <img width="214" alt="image" src="https://github.com/deephaven/vscode-deephaven/assets/1900643/4e6a932d-4da2-49e9-a255-b9cbf3c6f1a5">
- Better run icons for `"Run Deephaven File"` vs `"Run Deephaven Selected Lines"` (currently using \$(run-all) and 
\$(run) icons) which are shared by other commands such as the Python extension one
- ~Blank icon the same size as other product icons. This will help for things like our connection selector where we use icons to indicate the active connection but have to hack leading spaces to match indentation for the disconnected server names~ Looks like `codicons` already has `$(blank)`. Guess I missed it before.
- Others?

Vscode extensions have an icons contribution point where a font icon font (.woff) can provide additional icons.
https://code.visualstudio.com/api/references/icons-in-labels#icon-contribution-point

UPDATE: Here's what things currently look like:
**Status bar states**
<img width="215" alt="image" src="https://github.com/deephaven/vscode-deephaven/assets/1900643/4039b038-ccbd-402d-b223-7f58435deb8d">

**Quick pick menu states**
<img width="263" alt="image" src="https://github.com/deephaven/vscode-deephaven/assets/1900643/e5bcf830-b7c6-4d1e-bc47-ea51810f83a6">

**Run Buttons**
"Run Deephaven File" and "Run Deephaven Selected Lines" respectively
<img width="58" alt="image" src="https://github.com/deephaven/vscode-deephaven/assets/1900643/aee82ac6-76ad-483b-ae0a-91c22747ad5c">

**Comment by mofojed** [comment]
Maybe the Deephaven D should be shown there when connected? Similar to the GitHub Copilot icon being displayed when it is connected.

**Comment by bmingles** [comment]
@dsmmcken I just noticed a clause in vscode publishing docs regarding SVG images:

> Note: Due to security concerns, vsce will not publish extensions that contain user-provided SVG images.

https://code.visualstudio.com/api/working-with-extensions/publishing-extension#publishing-extensions

Not 100% sure yet how this impacts custom icon fonts.
