### ISSUE TITLE
Managed server attempts to use an already bound port

### ISSUE THREAD

**Issue by chipkent** [deephaven/vscode-deephaven#135]
I have a DH instance running on 10000 and 10001.  When I tried to run a managed instance, it attempted to run it on 10001 and failed.

**Comment by bmingles** [comment]
I just ran into this as well and created [Pip server conflicts with configured servers #137](https://github.com/deephaven/vscode-deephaven/issues/137) with a little more specifics. Going to close this one as a duplicate.
