### ISSUE TITLE
Not seeing all servers in config file

### ISSUE THREAD

**Issue by chipkent** [deephaven/vscode-deephaven#136]
I have a server running on 10000 and another on 10001.  Both are in my config.  When I refresh the servers, I only see the 10000 server that I'm already bound to.  The 10001 server never appears.

```
venv➜  deephaven-example-use-cases git:(risk_ui) ✗ cat ~/.vscode/settings 
{
  // Core servers
  "deephaven.coreServers": [
    "http://localhost:10000/",
    "http://localhost:10001/",
    "http://localhost:10002/",
  ]
}
```

<img width="331" alt="image" src="https://github.com/user-attachments/assets/6086545e-51d2-4acb-882f-c21e031744ab">

**Comment by chipkent** [comment]
... and yes, I made sure I can connect to both via the web browser.

**Comment by bmingles** [comment]
@chipkent that's very odd. 

2 things that come to mind:
1. Verify there isn't a workspace level `.vscode/settings.json` file overriding your user settings
2. Kill all instances of vscode and start again in case something is out of sorts

**Comment by vbabich** [comment]
@chipkent re-open if you are still seeing this issue.
