### ISSUE TITLE
Start Docker DH server from vscode extension with workspace defaults

### ISSUE THREAD

**Issue by bmingles** [deephaven/vscode-deephaven#16]
#7 has requested options for worker lifecycle management from inside of the extension. We may want to support this in multiple ways, but this ticket is to scoped to Docker specific configurations:

* General Config 
  * Commands to start / stop DH core running in Docker
  * Configuration to specify which version of DH Docker container to run
* Workspace Config
  * Automatically map the workspace folder opened in vscode to the data volume in the container
  * Run appropriate cmds / config to make the DH server aware of the workspace folder:
e.g. Maybe running the following to make it possible for scripts to reference each other (See https://github.com/deephaven/vscode-deephaven/issues/10):
    ```python
    import sys
    sys.path.append("/data/storage/notebooks")
    ```

**Comment by vbabich** [comment]
Can we use Docker extension for managing containers?

**Comment by dsmmcken** [comment]
There's plenty of docker extensions for managing docker. This sounds like significant scope creep.
