### ISSUE TITLE
Double arrow does not remember the last command run

### ISSUE THREAD

**Issue by chipkent** [deephaven/vscode-deephaven#2]
The double run arrow does not remember the last type of run that was done.  It always seems to “Run Deephaven File”, which is the first in the list.  If I select and run via a different mode, it isn’t sticky, so I have to keep hand selecting it each time, which is not a good UX.

**Comment by bmingles** [comment]
@chipkent This is a vscode bug that I plan to file an issue with them. Workaround is to close (or hide) dh output panels and then change the selection. It should be sticky in that scenario. It won't change if any dh panels are visible.

**Comment by bmingles** [comment]
Included in #1
