### ISSUE TITLE
Hard to find tabs (search / filter available panels)

### ISSUE THREAD

**Issue by chipkent** [deephaven/vscode-deephaven#49]
Plugin: `1.3.0 pre`

The following code produces many tabs.

```python
from deephaven import empty_table

for i in range(100):
    print(f"Making {i}")
    globals()[f"t{i}"] = empty_table(10).update(['X = i', 'Y = 10 * i'])
```

In the IDE, there is a nav to search for a tab by name.  That is missing here, so it can become difficult to find a tab if there are many.  Only scroll appears to be supported.

<img width="686" alt="image" src="https://github.com/user-attachments/assets/707a5026-62bb-4ec4-8de2-55725f1d27ed">

**Comment by mofojed** [comment]
@chipkent These tabs are native to VSCode itself. There's many ways you can customize the presentation of tabs within VS Code: https://code.visualstudio.com/docs/getstarted/userinterface#_tabs
For your case specifically:
> When you have more open items than can fit in the title area, you can use the Open Editors section in the Explorer view (available through the ... button) to display a dropdown list of tabbed items.

Granted it would also be nice to be able to click on the object in the Output panel and have it get focus, and/or see a list of the objects available on a connection, but hopefully the tab navigation can help in the meantime while we build out other features.

**Comment by bmingles** [comment]
[Panel Management #116](https://github.com/deephaven/vscode-deephaven/issues/116) took care of being able to re-open variables in panels. Still need to look into filtering / searching when dealing with long lists of panels.
