### ISSUE TITLE
No way to get a figure back after it is closed

### ISSUE THREAD

**Issue by chipkent** [deephaven/vscode-deephaven#50]
Plugin: `1.3.0 pre`

If I create a figure and close it, I have no way to get it back.  With a REPL, I could type some code to do it, but the current functionality is not great for this case.

**Comment by vbabich** [comment]
This could be related to #49 
We should be able to click the object in the Output panel and/or have Object Explorer panel.

**Comment by bmingles** [comment]
Addressed by #118
