### ISSUE TITLE
Weird stuff happens on disconnected file run

### ISSUE THREAD

**Issue by chipkent** [deephaven/vscode-deephaven#6]
1. Disconnect
2. Run > Deephaven file

This looks like it is trying to spin up an instance or connect or who knows what.  This is unexpected.

See the screenshot in https://docs.google.com/document/d/1ID1vobavzDerUArnFbBMiDPZrtaN6fNooc52uIhSbiY/edit.

**Comment by bmingles** [comment]
This may have been fixed. If I disconnect and then run a file, it reconnects and produces the result as expected as far as I can tell.

It does re-output any existing server logs on a fresh connection which is consistent with how code studio works if you refresh the page.

**Comment by bmingles** [comment]
I created https://github.com/deephaven/vscode-deephaven/issues/12 to discuss / design any improvements to log output on reconnect.
