### ISSUE TITLE
Log downloading workflow is weird

### ISSUE THREAD

**Issue by chipkent** [deephaven/vscode-deephaven#65]
I am testing `Download Logs`.  The workflow is a little weird.  When the button is clicked:
1. The location for the download is selected.
2. The log file gets opened.

The opening of the log file feels a little weird since the text is already in the `OUTPUT` for the console, but not opening it could also be weird.  Maybe the best thing is the current behavior, but I am just noting that the file opening seems somewhat repetitive in the current version.  If multiple connections were concurrently supported, maybe it doesn't feel repetitive.

**Comment by vbabich** [comment]
Closing this ticket unless @chipkent can add details
