### ISSUE TITLE
Error reporting does not work when line numbers are reported as `-1`

### ISSUE THREAD

**Issue by chipkent** [deephaven/vscode-deephaven#66]
I'm attempting to test error reporting.  When I get the `-1` line number in the error, error reporting does not work.  Since I always get the error, I can't test error reporting in any way.

See #9

**Comment by bmingles** [comment]
This is a side effect of the underlying bug impacting #9. There's not really anything we can do to match the line numbers if the underlying Python doesn't provide it. Going to close this as a duplicate. If / when we resolve the line number problem, this should go away.
