### ISSUE TITLE
Type `ui` where?

### ISSUE THREAD

**Issue by jjbrosnan** [deephaven/vscode-deephaven#69]
The README says "simply type `ui` to see available snippets".

I'm not sure where to type this. I've never used an extension like this from VSCode.

**Comment by bmingles** [comment]
@jjbrosnan snippets in vscode are languageid specific. The ones in the extension are associated with `python`, so you can just open any Python file and type `ui`. Should see options show up like:
<img width="611" alt="image" src="https://github.com/user-attachments/assets/ce8c7296-8a64-4505-8969-f51283243034">

**Comment by vbabich** [comment]
@bmingles can you update the readme?
