### ISSUE TITLE
DHC: Worker lifecycle management

### ISSUE THREAD

**Issue by chipkent** [deephaven/vscode-deephaven#7]
DHC worker management

In the context of DHC, a running server is synonymous with a worker.

- [Manage pip installed servers from extension #108](https://github.com/deephaven/vscode-deephaven/issues/108)
- Connect to running server (aka. conceptually creating new worker in the UI)
- Connect different editors to different running connections

~Created #16 to address Docker flavor of this~ UPDATE: Docker worker management was marked as wontfix

This should also address [1-to-1 execution model is too rigid #45](https://github.com/deephaven/vscode-deephaven/issues/45)

**Comment by dsmmcken** [comment]
There's plenty of vs code docker extensions to control docker, including official ones from docker.

**Comment by mofojed** [comment]
Re-opening for triage. This isn't just about Docker lifecycle management, this is about worker lifecycle management. Will need to consider for DHE cases as well. Probably will be an epic broken into multiple tickets.
For docker worker management, we can provide an example of how to do that with the existing Docker.
