### ISSUE TITLE
Plugin modules seem to not be recognized by IDE

### ISSUE THREAD

**Issue by alexpeters1208** [deephaven/vscode-deephaven#85]
When I type `import deephaven.plot.express`, the IDE does not seem to recognize that path as valid.
<img width="717" alt="Screenshot 2024-08-06 at 5 09 03 PM" src="https://github.com/user-attachments/assets/e51bba31-5df5-4d8f-901c-08690c1e1bee">
However, the code runs fine and produces the plot, so it must be a valid path. Seems to happen with deephaven.ui as well.

**Comment by bmingles** [comment]
@alexpeters1208 what server setup are you using? Docker, pip, etc?

**Comment by vbabich** [comment]
@alexpeters1208 did you have time to look at this?

**Comment by alexpeters1208** [comment]
I just did, thank you for the reminder, @vbabich. I am using a Docker setup. I did not have an active environment with all of the Python dependencies installed.
I see the reasoning behind this requirement, but in using Docker-DH from VSCode, creating a peripheral Python env just to get intellisense to work seems out of place. It's a very natural requirement if I'm running pip-DH.
I guess there is really no alternative for the Docker case?

**Comment by bmingles** [comment]
As of now, I don't know of another way. `vscode` intellisense is based on the workspace you are in, so it has to derive python module info from things it is aware of. Possible you could do something with Docker volumes, but ultimately vscode has to be able to look for things in a local path.

**Comment by alexpeters1208** [comment]
@bmingles Understandable. In the Docker case, does the VSCode plugin have knowledge of the container ID it's connecting to? If so, it may be possible to create a script / button / command / whatever to do something like the following:
```bash
docker exec container-id pip freeze >> tmp_vscode_requirements.txt
python -m venv tmp-vscode-venv && source tmp-vscode-venv/bin/activate && pip install -r tmp_vscode_requirements.txt
```
to create a local Python env with identical package contents to the running Docker container.

Granted, I can also run those commands manually, but it may be nice to have a button or something that creates an env identical to the container.

**Comment by bmingles** [comment]
@alexpeters1208 The extension does not have any awareness it's targeting a Docker server.

**Comment by alexpeters1208** [comment]
There was discussion about potentially mounting a Docker volume where the venv contents could be identified. This seems most promising. For Docker-DH, the Python packages are installed in a venv in the container at `/opt/deephaven/venv`. I guess that would be the thing to mount?

Closing as not planned - this has evolved into a feature request outside the scope of the initial complaint, and the initial complaint has a solution.
