### ISSUE TITLE
`deephaven.ui` dashboards do not get rendered out into their own window like the Deephaven IDE

### ISSUE THREAD

**Issue by alexpeters1208** [deephaven/vscode-deephaven#86]
It's not clear to me that dashboards in VSCode _should_ get rendered into their own window. This is just pointing out that they don't.
<img width="1464" alt="Screenshot 2024-08-06 at 5 20 23 PM" src="https://github.com/user-attachments/assets/931b8189-86e8-444d-a005-1d039bd9d2a5">

**Comment by bmingles** [comment]
@alexpeters1208 will have to think about this one if this is the best way or if we even have any other options.

Something to call out that is unique to `vscode` is that you can drag tabs outside of the current window, and they will open a new vscode instance that can live on another desktop or wherever you'd like. Things should remain connected such that this is now a separate dashboard. This doesn't address doing it automatically, but it's worth experimenting with to see what kind of new workflows are available here.

**Comment by vbabich** [comment]
Closing, working as expected.
