### ISSUE TITLE
Errors from previous session get dumped on first command

### ISSUE THREAD

**Issue by alexpeters1208** [deephaven/vscode-deephaven#87]
The Deephaven IDE has an annoying issue where when I start a new server session, it seems that the browser is still trying to find variables from the previous session, and shows errors in the console when they cannot be found.
<img width="1215" alt="Screenshot 2024-08-07 at 10 50 20 AM" src="https://github.com/user-attachments/assets/5e5988d6-1596-4f99-a24f-7e4f202b3dcc">

This is annoying, but I'm used to it.
In VSCode, these errors didn't show up till I executed code for the first time, and left me thinking something actually went wrong until the code completed.
<img width="1728" alt="Screenshot 2024-08-07 at 10 51 43 AM" src="https://github.com/user-attachments/assets/c0836a1c-a414-4d8d-8d3b-5e5b477cb3e0">

**Comment by bmingles** [comment]
@alexpeters1208 I believe this is a duplicate of [Smarter output logging between server connections #12](https://github.com/deephaven/vscode-deephaven/issues/12)

**Comment by alexpeters1208** [comment]
I think you're right.
